#! /usr/bin/bash 


CFLAGS=
CFLAGS="$CFLAGS -std=c++17" 

CFLAGS="$CFLAGS -I."
CFLAGS="$CFLAGS -I./abseil-cpp"
CFLAGS="$CFLAGS -I./benchmark/include"
#CFLAGS="$CFLAGS -I./googletest/googletest/include "
#CFLAGS="$CFLAGS -I./googletest/googlemock/include "
CFLAGS="$CFLAGS -I./benchmark/googletest/googlemock/include "
CFLAGS="$CFLAGS -I./benchmark/googletest/googletest/include "
CFLAGS="$CFLAGS -I./xor_singleheader/include "
CFLAGS="$CFLAGS -I./CRoaring/cpp "
CFLAGS="$CFLAGS -I./CRoaring/include "
CFLAGS="$CFLAGS -I./csv-parser "
CFLAGS="$CFLAGS -I./leveldb/include"
# CFLAGS="$CFLAGS -I./protobuf/src"

for f in common/*.cc; do 
  echo $f 
  g++ -c ${CFLAGS} $f 2>&1 | tee $f.log
done;

for f in *.cc; do 
  echo $f 
  g++ -c ${CFLAGS} $f 2>&1 | tee $f.log
done;





